services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: course
    container_name: my-postgresql-docker-compose
    volumes:
      - postgresql-volume:/var/lib/postgresql

  my-app:
    build: .
    image: my-app:v1.3

    ports:
      - 8585:9191
    container_name: my-app-docker-compose
    depends_on:
      - db
  client:
    image: my-client-app:v1
    ports:
      - 8686:8080
    container_name: my-client-app-container
    depends_on:
      - my-app

volumes:
  postgresql-volume: